///<reference path="./jaydata.d.ts" />

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                      oData  V3  TypeScript                              /////////
//////////////////////////////////////////////////////////////////////////////////////*/


declare module SeguimientoEleccion.Web.Models {
  export class Elector extends $data.Entity {
    constructor();
    constructor(initData: { Id?: number; Nombre?: string; Colegio?: string; Punteado?: boolean; });
    Id: number;
    Nombre: string;
    Colegio: string;
    Punteado: boolean;
    
  }
  
}

declare module Default {
  export class Container extends $data.EntityContext {
    onReady(): $data.IPromise;
    onReady(handler: (context: Container) => void): $data.IPromise;
    
    Electores: $data.EntitySet<SeguimientoEleccion.Web.Models.Elector>;
    
  }

}
