// <auto-generated />
namespace SeguimientoEleccion.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Colegios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Colegios));
        
        string IMigrationMetadata.Id
        {
            get { return "201409171358119_Colegios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
